server:
  port: 8897
spring:
  datasource:
    url: jdbc:mysql://140.246.94.21:3306/novel?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&aserverTimezone=UTC
    username: CVast
    password: hch980905
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: club.cvast.domain
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml
