server:
  port: 7080
spring:
  datasource:
    url: jdbc:mysql://140.246.94.21:3306/novel?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&aserverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.jxit.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml
