server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&aserverTimezone=UTC
    username: root
    password: hch980905
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: club.cvast.domain
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml
logging:
  config: classpath:config/logback-spring.xml
  path: data/logs